### ISSUE TITLE
Functions to develop (Meeting on Jan 13 0900)

### ISSUE THREAD

**Issue by imtvwy** [UBC-MDS/bc_covid_simple_eda#3]
Here are the 4 functions to be included in our package and the person assigned
1. dataframe getData(startDate, endDate, ageGroup, sex) - Vadim
2. showSummaryStat(startDate, endDate) - e.g. daily new case - Vanessa
3. plotLineByDate(startDate, endDate, movingAvgRange=#Days) - Lianna
4. plotHistByCond(startDate, endDate, condition=Age/Region) - John

DateFormat: YYYY-MM-DD

**Comment by liannah** [comment]
The according issues were created and the final modifications of the arguments can be visible in the docstring.
